# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e43f20f6047f270984edda619f039292f9448619a1a037e3429ca14c59b022cd65089fa8f73f7779e28a32feb61be922b024af0a09a3c45fe6f24f0e47931d15

test:
  secret_key_base: bd3a14f2e35238bddb3239a0775e0bfee1d280854722aaef530be39f10f6d9109fe0f7f95bc61ffefacb5598e02005b9e6f348c6c58ed0b1754abf5c0f276649

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
